spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: h2
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:./localdb/stx'
    username: 'h2y'
    password: 'h2p'